accounts/urls.py
from django.urls import path

from .views import LoginView, logout_view, SignUpView, profile_view

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<int:pk>', profile_view, name='profile'),
]

blog/urls.py
from django.urls import path
from .views import (HomeView, CreateBlog, BlogDetailView,
                    UpdateBlog, DeleteBlog)


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', CreateBlog.as_view(), name='create'),
    path('<slug:slug>/', BlogDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', UpdateBlog.as_view(), name='update'),
    path('<slug:slug>/delete/', DeleteBlog.as_view(), name='delete'),
]

django_assignment_II_v2/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL,
    #                       document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/utils/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">My<span class="font-weight-lighter">Blog</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse ml-auto" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link active" href="{% url 'home' %}">Home</a>
          <a class="nav-item nav-link active"
             href="{% url 'accounts:profile' request.user.id %}">Profile</a>
          <a class="nav-item nav-link active"
             href="{% url 'accounts:logout' %}">LogOut</a>
        </div>
      </div>
      {% else %}
      <div class="collapse navbar-collapse ml-auto" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <a class="nav-item nav-link active"
           href="{% url 'accounts:signup' %}">SignUp</a>
        <a class="nav-item nav-link active"
           href="{% url 'accounts:login' %}">LogIn</a>
      </div>
    </div>
    {% endif %}
  </div>
</nav>